scripting done

diff --git a/bash_scripts/put-object b/bash_scripts/put-object
--- a/bash_scripts/put-object
+++ b/bash_scripts/put-object
@@ -11,19 +11,14 @@ if [ -z "$1" ]; then
     exit 1
 fi
 
-output_dir="/tmp/s3-bash-scripts"
+#Check for bucket name
+if [ -z "$2" ]; then
+    echo "The file path required to be uploaded is missing, give the path next to bucket"
+    exit 1
+fi
 
-rm -r $output_dir
-mkdir -p
 
-num_files=$((RANDOM % 6 + 5))
-
-for ((i=1; i<=num_files; i++)); do
-    filename="$output_dir/$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 8).txt"
-    head -c $((RANDOM % 1000 + 100)) /dev/urandom > "$filename"
-    echo "Created: $filename"
-done
-
-tree $output_dir
-
-aws s3api sync $output_dir s3://$1/files
+aws s3api put-object \
+--bucket $1 \
+--body $2 \
+--key $(basename "$2")
